language: java
dist: trusty

before_install:
  - rm -rf $HOME/.m2/repository/io/vlingo
  - cp .travis/settings.xml $HOME/.m2/settings.xml
  # Force caching of maven plugins used during deploy phase
  - mvn deploy:help versions:help help:help

script:
  - mvn install

before_cache:
  - rm -rf $HOME/.m2/repository/io/vlingo
cache:
  directories:
    - $HOME/.m2/repository

deploy:
  - provider: script
    script: "mvn deploy -DskipTests"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: "mvn deploy -DskipTests"
    skip_cleanup: true
    on:
      branch: master

notifications:
  slack:
    secure: Nl+HJNcVo55EuvX0qWr4IcUK9dIfX9TEeoaySsfOjNgcUMYuwbR07NJCk3LNfhBbn+4W9ls2Xjsk4dhWzaLfXrGV8cqg7t9MgfXTfHz5A/3T6tQc17BPvC7hc6j3lWGpKo40tCqFpsJFTW24TjtCKwn9VKqRLm65AE/dPk6cRAHvUNUf4yFXss/qG/SQhAsso5Je0MUOculRtRGKETvOM9uwJohppLL52s7qTuz9a5NjD76Pmp0vGfr75gNR2BOFuLvMV4RunpT4ms2hVyU2sQDDbX+bcQgbc3tD1LXWqg6VzgqVJmJ4tFnb2XMN3O1bHBoy3o3jNBbmWCK1ekxIJZbVkgAUluFXWXYYvgFIQDvgQn16GRYlsu6+IkLZe8SZ0610cFu2cx1jWEc9SRvj/TPpxkj417OD187vZAUGKcpv3VqX2mdc96Y1WuHoouPZvl6QQqR2B9OG99LiU5DE1dh5cVWPqlrUgWdto5Y4LCnHExFtDG/Vu3EA0+lwTS/K1fuE7eKnAIvpRX3aeTjF7TwAMXMfuaCU1bcXx33WnZgerE02Tf4vkxaWwBsHkBxlaoVxHUbxXfC5jmonWk1wAW2RzYL73aHxSu6HqteXgbiPKjlSfOFDyI6y16Ey90WvLo/S2kpz4BiTKx+6Xo9E4bVHRBlKrbRKLaTfkTyNhuE=
